FROM ubuntu:20.04

WORKDIR /usr/local

RUN apt-get update -y && apt-get install maven -y && apt-get install openjdk-14-jdk -y

COPY ./sdql-service /usr/local/

RUN mvn package

RUN mkdir -p /usr/local/database

RUN mkdir -p /usr/local/database/data

ENTRYPOINT ["java","-cp","application/target/application-1.0-SNAPSHOT.jar","sd.nosql.Server"]
