FROM maven:3.6.3-openjdk-14-slim

WORKDIR /usr/local

COPY ./sdql-service /usr/local/

RUN mvn package -DskipTests

ENTRYPOINT ["java","-cp","application/target/application-1.0-SNAPSHOT.jar","sd.nosql.Server"]